// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/DarkAIRenderMusicPlayer-_lYzRl/App.tsx": () => import("../components/mockups/templates/DarkAIRenderMusicPlayer-_lYzRl/App.tsx"),
  "./components/mockups/templates/NorthBeachOpenMicFlyer-3hR67M/OpenMicFlyer.tsx": () => import("../components/mockups/templates/NorthBeachOpenMicFlyer-3hR67M/OpenMicFlyer.tsx")
};
